Fix 404

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,8 +28,8 @@ jobs:
           git pull origin main || { echo 'Git pull failed' ; exit 1; }
           
           # Check if pm2 process is running and restart or start it
-          if pm2 list | grep -q '0'; then
-            pm2 restart 0 || { echo 'PM2 restart failed' ; exit 1; }
+          if pm2 list | grep -q '2'; then
+            pm2 restart 2 || { echo 'PM2 restart failed' ; exit 1; }
           else
             pm2 start /home/ubuntu/code/Frontend --name 'app' || { echo 'PM2 start failed' ; exit 1; }
           fi
