Sidebar Added

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -28,9 +28,6 @@ jobs:
           git pull origin main || { echo 'Git pull failed' ; exit 1; }
           
           # Check if pm2 process is running and restart or start it
-          if pm2 list | grep -q '2'; then
-            pm2 restart 2 || { echo 'PM2 restart failed' ; exit 1; }
-          else
-            pm2 start /home/ubuntu/code/Frontend --name 'app' || { echo 'PM2 start failed' ; exit 1; }
+          pm2 restart 1 || { echo 'PM2 restart failed' ; exit 1; }
           fi
           EOF
